items:
  - name: 'coal chestplate' # Displayname item
    material: 'IRON_CHESTPLATE' # Item material
    custommodeldata: 1 # De juiste custommodeldata
  - name: 'diamond sword'
    material: 'DIAMOND_SWORD'
    custommodeldata: 123