name: ResourcepackFix
version: '1.0-SNAPSHOT'
main: eu.camonetwork.resourcepackfix.Main
api-version: '1.15'

commands:
  resourcepackfix:
    description: Main command
    default: yes
    aliases:
      - rpf
      - rpfix
      - texturepackfix
      - tpf
      - tpfix